services:
  rocket:
    container_name: rocket-dev
    build: .
    working_dir: /workspace
    volumes:
      - ".:/workspace"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0}
      - QT_X11_NO_MITSHM=1
      - SDL_AUDIODRIVER=dummy
      - SDL_RENDER_DRIVER=software
      - LIBGL_ALWAYS_INDIRECT=1
    stdin_open: true
    tty: true
