services:
  python-sand:
    container_name: python-sand-dev
    build: .
    working_dir: /workspace
    volumes:
      - "../:/workspace"
      - "/tmp/.X11-unix:/tmp/.X11-unix"   # share host X11 socket
    environment:
      - QT_X11_NO_MITSHM=1                # avoids shared-memory errors
      - DISPLAY=host.docker.internal:0
    stdin_open: true
    tty: true